-- MySQL Script generated by MySQL Workbench
-- Mon Jul 26 10:06:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medisource
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medisource
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medisource` DEFAULT CHARACTER SET utf8 ;
USE `medisource` ;

-- -----------------------------------------------------
-- Table `medisource`.`systeme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`systeme` (
  `id_systeme` INT NOT NULL AUTO_INCREMENT,
  `name_systeme` VARCHAR(255) NULL,
  `desc_systeme` TEXT(60000) NULL,
  `image_systeme` VARCHAR(255) NULL,
  PRIMARY KEY (`id_systeme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`organe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`organe` (
  `id_organe` INT NOT NULL AUTO_INCREMENT,
  `name_organe` VARCHAR(255) NULL,
  `desc_organe` TEXT(60000) NULL,
  `image_organe` VARCHAR(255) NULL,
  `systeme_id_systeme` INT NOT NULL,
  PRIMARY KEY (`id_organe`),
  INDEX `fk_organe_systeme1_idx` (`systeme_id_systeme` ASC),
  CONSTRAINT `fk_organe_systeme1`
    FOREIGN KEY (`systeme_id_systeme`)
    REFERENCES `medisource`.`systeme` (`id_systeme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`maladie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`maladie` (
  `id_maladie` INT NOT NULL AUTO_INCREMENT,
  `name_maladie` VARCHAR(255) NULL,
  `desc_maladie` TEXT(60000) NULL,
  `image_maladie` VARCHAR(255) NULL,
  PRIMARY KEY (`id_maladie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`traitement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`traitement` (
  `id_traitement` INT NOT NULL AUTO_INCREMENT,
  `name_traitement` VARCHAR(255) NULL,
  `desc_traitement` TEXT(60000) NULL,
  `image_traitement` VARCHAR(255) NULL,
  PRIMARY KEY (`id_traitement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(255) NULL,
  `email_user` VARCHAR(255) NULL,
  `pass_user` VARCHAR(255) NULL,
  `statut_user` INT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`lien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`lien` (
  `id_lien` INT NOT NULL AUTO_INCREMENT,
  `name_lien` VARCHAR(255) NULL,
  `desc_lien` TEXT(60000) NULL,
  PRIMARY KEY (`id_lien`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`maladie_has_organe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`maladie_has_organe` (
  `maladie_id_maladie` INT NOT NULL,
  `organe_id_organe` INT NOT NULL,
  PRIMARY KEY (`maladie_id_maladie`, `organe_id_organe`),
  INDEX `fk_maladie_has_organe_organe1_idx` (`organe_id_organe` ASC),
  INDEX `fk_maladie_has_organe_maladie1_idx` (`maladie_id_maladie` ASC),
  CONSTRAINT `fk_maladie_has_organe_maladie1`
    FOREIGN KEY (`maladie_id_maladie`)
    REFERENCES `medisource`.`maladie` (`id_maladie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maladie_has_organe_organe1`
    FOREIGN KEY (`organe_id_organe`)
    REFERENCES `medisource`.`organe` (`id_organe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`traitement_has_maladie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`traitement_has_maladie` (
  `traitement_id_traitement` INT NOT NULL,
  `maladie_id_maladie` INT NOT NULL,
  PRIMARY KEY (`traitement_id_traitement`, `maladie_id_maladie`),
  INDEX `fk_traitement_has_maladie_maladie1_idx` (`maladie_id_maladie` ASC),
  INDEX `fk_traitement_has_maladie_traitement1_idx` (`traitement_id_traitement` ASC),
  CONSTRAINT `fk_traitement_has_maladie_traitement1`
    FOREIGN KEY (`traitement_id_traitement`)
    REFERENCES `medisource`.`traitement` (`id_traitement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_traitement_has_maladie_maladie1`
    FOREIGN KEY (`maladie_id_maladie`)
    REFERENCES `medisource`.`maladie` (`id_maladie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`traitement_has_lien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`traitement_has_lien` (
  `traitement_id_traitement` INT NOT NULL,
  `lien_id_lien` INT NOT NULL,
  PRIMARY KEY (`traitement_id_traitement`, `lien_id_lien`),
  INDEX `fk_traitement_has_lien_lien1_idx` (`lien_id_lien` ASC),
  INDEX `fk_traitement_has_lien_traitement1_idx` (`traitement_id_traitement` ASC),
  CONSTRAINT `fk_traitement_has_lien_traitement1`
    FOREIGN KEY (`traitement_id_traitement`)
    REFERENCES `medisource`.`traitement` (`id_traitement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_traitement_has_lien_lien1`
    FOREIGN KEY (`lien_id_lien`)
    REFERENCES `medisource`.`lien` (`id_lien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`maladie_has_lien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`maladie_has_lien` (
  `maladie_id_maladie` INT NOT NULL,
  `lien_id_lien` INT NOT NULL,
  PRIMARY KEY (`maladie_id_maladie`, `lien_id_lien`),
  INDEX `fk_maladie_has_lien_lien1_idx` (`lien_id_lien` ASC),
  INDEX `fk_maladie_has_lien_maladie1_idx` (`maladie_id_maladie` ASC),
  CONSTRAINT `fk_maladie_has_lien_maladie1`
    FOREIGN KEY (`maladie_id_maladie`)
    REFERENCES `medisource`.`maladie` (`id_maladie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maladie_has_lien_lien1`
    FOREIGN KEY (`lien_id_lien`)
    REFERENCES `medisource`.`lien` (`id_lien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`organe_has_lien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`organe_has_lien` (
  `organe_id_organe` INT NOT NULL,
  `lien_id_lien` INT NOT NULL,
  PRIMARY KEY (`organe_id_organe`, `lien_id_lien`),
  INDEX `fk_organe_has_lien_lien1_idx` (`lien_id_lien` ASC),
  INDEX `fk_organe_has_lien_organe1_idx` (`organe_id_organe` ASC),
  CONSTRAINT `fk_organe_has_lien_organe1`
    FOREIGN KEY (`organe_id_organe`)
    REFERENCES `medisource`.`organe` (`id_organe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organe_has_lien_lien1`
    FOREIGN KEY (`lien_id_lien`)
    REFERENCES `medisource`.`lien` (`id_lien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medisource`.`systeme_has_lien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medisource`.`systeme_has_lien` (
  `systeme_id_systeme` INT NOT NULL,
  `lien_id_lien` INT NOT NULL,
  PRIMARY KEY (`systeme_id_systeme`, `lien_id_lien`),
  INDEX `fk_systeme_has_lien_lien1_idx` (`lien_id_lien` ASC),
  INDEX `fk_systeme_has_lien_systeme1_idx` (`systeme_id_systeme` ASC),
  CONSTRAINT `fk_systeme_has_lien_systeme1`
    FOREIGN KEY (`systeme_id_systeme`)
    REFERENCES `medisource`.`systeme` (`id_systeme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_systeme_has_lien_lien1`
    FOREIGN KEY (`lien_id_lien`)
    REFERENCES `medisource`.`lien` (`id_lien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
